create table if not exists public.users (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) <= 120),
  email text not null unique check (char_length(email) <= 320),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.users enable row level security;

create policy "Authenticated users can read users"
  on public.users
  for select
  to authenticated
  using (true);

create policy "Authenticated users can insert users"
  on public.users
  for insert
  to authenticated
  with check (true);

create policy "Authenticated users can update users"
  on public.users
  for update
  to authenticated
  using (true)
  with check (true);

create policy "Authenticated users can delete users"
  on public.users
  for delete
  to authenticated
  using (true);
